### ISSUE TITLE
Envoy unable to start with v8 filter

### ISSUE THREAD

**Issue by theganyo** [envoyproxy/envoy-wasm#136]
*Description*:
I built from head [36e3280280163cad1a905650f1425a1505400892], recompiled the wasm example using latest emscripten (1.38.41), modified the envoy.yaml to run using the v8 engine (and removed `allow_precompiled: true`) and attempted to start envoy. It immediately crashes. (Note that this works using the wavm engine.)

*Config*:
```
static_resources:
  listeners:
  - name: main
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: auto
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: web_service
          http_filters:
          - name: envoy.wasm
            config:
              vm_id: "my_vm_id"
              root_id: "my_root_id"
              vm_config:
                # vm: "envoy.wasm.vm.wavm"
                vm: "envoy.wasm.vm.v8"
                code:
                  filename: "/Users/theganyo/dev/envoy-wasm/examples/wasm/envoy_filter_http_wasm_example.wasm"
                # allow_precompiled: true
          - name: envoy.router
            config: {}
  - name: staticreply
    address:
      socket_address:
        address: 127.0.0.1
        port_value: 8099
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: auto
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                direct_response:
                  status: 200
                  body:
                    inline_string: "example body\n"
          http_filters:
          - name: envoy.router
            config: {}

  clusters:
  - name: web_service
    connect_timeout: 0.25s
    type: static
    lb_policy: round_robin
    hosts:
    - socket_address:
        address: 127.0.0.1
        port_value: 8099
admin:
  access_log_path: "/dev/null"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 8001
```

*Call Stack*:
```
#
# Fatal process OOM in WasmCodeManager::NewNativeModule
#

[2019-08-16 15:14:34.585][9741908][critical][backtrace] [bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:81] Caught Illegal instruction: 4, suspect faulting address 0x1079c6dd2
[2019-08-16 15:14:34.585][9741908][critical][backtrace] [bazel-out/darwin-fastbuild/bin/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:69] Backtrace (use tools/stack_decode.py to get line numbers):
[1]    44896 illegal hardware instruction  /Users/theganyo/dev/envoy-wasm/bazel-bin/source/exe/envoy-static -c
```
