### ISSUE TITLE
nodeMetadataStruct does not work in native VM

### ISSUE THREAD

**Issue by kyessenov** [envoyproxy/envoy-wasm#15]
nodeMetadataStruct called inside onConfigure returns an empty struct for an envoy with non-empty node metadata.

**Comment by jplevyak** [comment]
onConfigure is only called if there is a non-empty configuration. 

If you just want to get called when the VM starts up use the onStart hook.

See github.com/jplevyak/enovy-wasm on the wasm-node-metadata flag for details.

 I added a dummy configuration and it prints out the metadata.  I also used onStart to print out the
metadata.

We need docs.  I am opening an issue for that.

**Comment by jplevyak** [comment]
https://github.com/envoyproxy/envoy-wasm/issues/16

**Comment by kyessenov** [comment]
Here is my envoy.yaml:
```yaml
node:
  id: test
  metadata:
    labels: test
static_resources:
  listeners:
  - name: main
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 8080
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: auto
          route_config:
            name: local_route
            virtual_hosts:
            - name: local_service
              domains:
              - "*"
              routes:
              - match:
                  prefix: "/"
                route:
                  cluster: web_service
          http_filters:
          - name: envoy.wasm
            config:
              vm_config:
                vm: "envoy.wasm.vm.null"
                code:
                  inline_string: "envoy.wasm.metadata_exchange"
              configuration: "test"
          - name: envoy.router
            config: {}
...
```

Here is the code in the plugin:
```c++
void PluginContext::onConfigure(std::unique_ptr<WasmData> /* configuration */) {
  logInfo("configuring metadata exchange");

  // populate and encode node metadata
  auto metadata = nodeMetadataStruct();
  logInfo("metadata struct " + std::to_string(metadata.fields().size()));
}
```

Here is the output:
```
[2019-05-28 11:47:07.001][6634][info][wasm] [source/extensions/common/wasm/wasm.cc:1033] wasm log: configuring metadata exchange
[2019-05-28 11:47:07.001][6634][info][wasm] [source/extensions/common/wasm/wasm.cc:1033] wasm log: metadata struct 0
```

As you can see, node metadata does not propagate.
