### ISSUE TITLE
Segfault while parsing CEL: proxy 1.6-alpha

### ISSUE THREAD

**Issue by mandarjog** [envoyproxy/envoy-wasm#497]
Istio-proxy: Version 1.6-alpha.f63181a5c5d886aa309f67ab098897e85f3b573c
With the following stats config:
```yaml
 - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_OUTBOUND
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
            subFilter:
              name: envoy.router
      proxy:
        proxyVersion: ^1\.6.*
    patch:
      operation: INSERT_BEFORE
      value:
        name: istio.stats
        typed_config:
          '@type': type.googleapis.com/udpa.type.v1.TypedStruct
          type_url: type.googleapis.com/envoy.config.filter.http.wasm.v2.Wasm
          value:
            config:
              configuration: |
                {
                  "debug": "false",
                  "stat_prefix": "istio",
                  "metrics": [
                      {
                        "name": "requests_total",
                        "dimensions": {
                           "request_operation": "istio.operationId"
                      }
                      }
                  ]
                }
              root_id: stats_outbound
              vm_config:
                code:
                  local:
                    inline_string: envoy.wasm.stats
                runtime: envoy.wasm.runtime.null
                vm_id: stats_outbound
```

```c++
[Envoy (Epoch 0)] [2020-04-28 16:46:13.742][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:104] Caught Se
gmentation fault, suspect faulting address 0x0
[Envoy (Epoch 0)] [2020-04-28 16:46:13.742][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:91] Backtrace
(use tools/stack_decode.py to get line numbers):
[Envoy (Epoch 0)] [2020-04-28 16:46:13.742][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:92] Envoy vers
ion: 7598da631d123f45b5f7e142848e59f94b60bfde/1.14.0-dev/Clean/RELEASE/BoringSSL
[Envoy (Epoch 0)] [2020-04-28 16:46:13.742][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #0: __rest
ore_rt [0x7f305ce74890]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.755][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #1: antlr4
::atn::ParserATNSimulator::execATN() [0x5622ca09503f]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.767][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #2: antlr4
::atn::ParserATNSimulator::adaptivePredict() [0x5622ca094a20]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.778][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #3: cel_gr
ammar::CelParser::unary() [0x5622ca05f034]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.789][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #4: cel_gr
ammar::CelParser::calc() [0x5622ca05e446]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.799][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #5: cel_gr
ammar::CelParser::relation() [0x5622ca05db88]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.812][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #6: cel_gr
ammar::CelParser::conditionalAnd() [0x5622ca05d468]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.824][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #7: cel_gr
ammar::CelParser::conditionalOr() [0x5622ca05cc26]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.836][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #8: cel_gr
ammar::CelParser::expr() [0x5622ca05c64e]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.847][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #9: cel_gr
ammar::CelParser::start() [0x5622ca05c23d]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.858][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #10: googl
e::api::expr::parser::ParseWithMacros() [0x5622ca048072]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.869][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #11: googl
e::api::expr::parser::Parse() [0x5622ca047ea5]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.880][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #1[9/1853$
::Extensions::Common::Wasm::CreateExpressionFactory::create()::{lambda()#1}::operator()() [0x5622c95f1caf]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.892][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #13: std::
__1::__invoke_void_return_wrapper<>::__call<>() [0x5622c95f1b47]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.904][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #14: Envoy
::Extensions::Common::Wasm::Exports::call_foreign_function() [0x5622c95e8f9c]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.915][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #15: Envoy
::Extensions::Common::Wasm::Null::Plugin::Stats::PluginRootContext::addStringExpression() [0x5622c8d2be73]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.928][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #16: Envoy
::Extensions::Common::Wasm::Null::Plugin::Stats::PluginRootContext::initializeDimensions() [0x5622c8d2a07f]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.941][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #17: Envo$::Extensions::Common::Wasm::Null::Plugin::Stats::PluginRootContext::onConfigure() [0x5622c8d2da97]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.955][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #18: std:$__1::__function::__func<>::operator()() [0x5622c8dcdc7b]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.968][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #19: Envo$::Extensions::Common::Wasm::Context::onConfigure() [0x5622c95d746e]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.982][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #20: Envo$::Extensions::Common::Wasm::getOrCreateThreadLocalWasm() [0x5622c95fc844]
[Envoy (Epoch 0)] [2020-04-28 16:46:13.994][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #21: std:$__1::__function::__func<>::operator()() [0x5622c911d4d7]
[Envoy (Epoch 0)] [2020-04-28 16:46:14.008][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #22: std:$__1::__function::__func<>::operator()() [0x5622ca303cb8]
[Envoy (Epoch 0)] [2020-04-28 16:46:14.022][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #23: std:$__1::__function::__func<>::operator()() [0x5622ca304ee8]
[Envoy (Epoch 0)] [2020-04-28 16:46:14.035][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #24: Envo$::Event::DispatcherImpl::runPostCallbacks() [0x5622ca377fc6]
[Envoy (Epoch 0)] [2020-04-28 16:46:14.049][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #25: even$_process_active_single_queue [0x5622ca6c2fd6]
[Envoy (Epoch 0)] [2020-04-28 16:46:14.063][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #26: even$_base_loop [0x5622ca6c1b5e]
[Envoy (Epoch 0)] [2020-04-28 16:46:14.077][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #27: Envo$::Server::WorkerImpl::threadRoutine() [0x5622ca36ecb8]
[Envoy (Epoch 0)] [2020-04-28 16:46:14.089][31][critical][backtrace] [bazel-out/k8-opt/bin/external/envoy/source/server/_virtual_includes/backtrace_lib/server/backtrace.h:96] #28: Envo$::Thread::ThreadImplPosix::ThreadImplPosix()::$_0::__invoke() [0x5622ca88b533]
[Envoy (Epoch 0)] [2020-04-28
```
